GET http://localhost:6135/api/:id
Content-Type: application/json

###
POST http://localhost:6135/api
Content-Type: application/json

{
  "name": "Spencer",
  "description": "Original"
}

###
PUT http://localhost:6135/api/:id
Content-Type: application/json

{
  "name": "Sponcer",
  "description": "Alternative"
}

###
DELETE http://localhost:6135/api/:id
Content-Type: application/json
